-- Seed script for packages
INSERT INTO packages (id, producer_id, name, slug, description, price, max_participants, duration, wines, includes, excludes, location_details, available_days, available_times, languages, difficulty_level, age_restriction, special_requirements, cancellation_policy, images) VALUES

-- Cantina Rossi & Figli packages
('pkg11111-1111-1111-1111-111111111111',
 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
 'Degustazione Premium Barolo',
 'degustazione-premium-barolo',
 'Esperienza esclusiva dedicata al re dei vini piemontesi. Degustazione guidata di 5 Barolo DOCG di diverse annate (2015-2020) con spiegazione delle caratteristiche organolettiche, territori di provenienza e tecniche di vinificazione. Include visita alle storiche cantine sotterranee del XVIII secolo e abbinamenti con formaggi DOP locali.',
 89.50,
 8,
 120,
 '[{"name": "Barolo Tradizionale 2018", "type": "red", "vintage": 2018, "alcohol_content": 14.5, "grape_varieties": ["Nebbiolo"], "tasting_notes": "Note di ciliegia matura, spezie dolci, tartufo e liquirizia. Tannini eleganti e persistenza notevole.", "serving_temperature": "18-20°C"}, {"name": "Barolo Riserva 2016", "type": "red", "vintage": 2016, "alcohol_content": 15.0, "grape_varieties": ["Nebbiolo"], "tasting_notes": "Profumi intensi di rosa appassita, tabacco e cacao. Struttura importante e finale lungo.", "serving_temperature": "18-20°C"}, {"name": "Barolo Chinato", "type": "fortified", "vintage": 2017, "alcohol_content": 16.5, "grape_varieties": ["Nebbiolo"], "tasting_notes": "Aromatizzato con china e spezie. Perfetto per la meditazione.", "serving_temperature": "16-18°C"}]',
 '["Degustazione guidata 5 vini Barolo", "Visita cantina storica", "Aperitivo di benvenuto", "Abbinamenti formaggi DOP", "Guida esperta sommelier", "Materiale didattico"]',
 '["Trasporto", "Pranzo completo", "Acquisto vini"]',
 '{"address": "Via delle Vigne 12, Barolo", "meeting_point": "Ingresso principale cantina", "parking_available": true, "accessibility_notes": "Accessibile a persone con mobilità ridotta", "coordinates": {"latitude": 44.6146, "longitude": 7.9404}}',
 '["friday", "saturday", "sunday"]',
 '["14:00", "16:00", "18:00"]',
 '["it", "en"]',
 'intermediate',
 18,
 'È consigliato non guidare dopo la degustazione. Sconsigliato in gravidanza.',
 'Cancellazione gratuita fino a 48 ore prima. Cancellazione oltre i termini: rimborso del 50%.',
 '[]'),

('pkg22222-2222-2222-2222-222222222222',
 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
 'Tour delle Langhe con Degustazione',
 'tour-langhe-degustazione',
 'Esperienza completa nelle Langhe patrimonio UNESCO. Tour guidato tra i vigneti con spiegazione del territorio e delle tradizioni vinicole, seguito da degustazione di 6 vini tipici (Barolo, Barbaresco, Dolcetto, Barbera) con pranzo tipico piemontese. Include trasporto in minibus da Alba.',
 145.00,
 12,
 300,
 '[{"name": "Barbera d''Alba", "type": "red", "vintage": 2021, "grape_varieties": ["Barbera"], "tasting_notes": "Fruttato e fresco, note di ciliegia e spezie dolci."}, {"name": "Dolcetto d''Alba", "type": "red", "vintage": 2022, "grape_varieties": ["Dolcetto"], "tasting_notes": "Morbido e armonico, profumi di frutti rossi."}, {"name": "Barbaresco", "type": "red", "vintage": 2019, "grape_varieties": ["Nebbiolo"], "tasting_notes": "Elegante e complesso, note di rosa e spezie."}, {"name": "Barolo", "type": "red", "vintage": 2018, "grape_varieties": ["Nebbiolo"], "tasting_notes": "Potente e strutturato, lungo e persistente."}]',
 '["Trasporto da/per Alba", "Guida esperta", "Degustazione 6 vini", "Pranzo tipico piemontese", "Visita vigneti", "Materiale didattico"]',
 '["Extra bevande", "Acquisti personali"]',
 '{"address": "Ritrovo Piazza Duomo, Alba", "meeting_point": "Fontana centrale", "parking_available": false, "accessibility_notes": "Tour non adatto a persone con difficoltà motorie"}',
 '["saturday", "sunday"]',
 '["09:30"]',
 '["it", "en", "de"]',
 'beginner',
 18,
 'Abbigliamento comodo e scarpe chiuse. Sconsigliato in caso di pioggia forte.',
 'Cancellazione gratuita fino a 72 ore prima. Oltre i termini nessun rimborso.',
 '[]'),

-- Tenuta Bella Vista packages
('pkg33333-3333-3333-3333-333333333333',
 'b2c3d4e5-f6g7-8901-bcde-f23456789012',
 'Chianti Classico Experience',
 'chianti-classico-experience',
 'Immersione totale nel mondo del Chianti Classico. Degustazione orizzontale di 4 Chianti Classico di diverse annate (2019-2022) e verticale di Riserva, seguita da assaggio di Super Tuscan premium. Include visita alla barricaia, spiegazione del territorio del Gallo Nero e pranzo con vista panoramica sulle colline del Chianti.',
 125.00,
 10,
 180,
 '[{"name": "Chianti Classico 2022", "type": "red", "vintage": 2022, "grape_varieties": ["Sangiovese", "Canaiolo"], "tasting_notes": "Giovane e fresco, note di frutti rossi e viola."}, {"name": "Chianti Classico Riserva 2020", "type": "red", "vintage": 2020, "grape_varieties": ["Sangiovese"], "tasting_notes": "Strutturato e complesso, note di spezie e legno."}, {"name": "Super Tuscan", "type": "red", "vintage": 2019, "grape_varieties": ["Sangiovese", "Merlot", "Cabernet Sauvignon"], "tasting_notes": "Potente ed elegante, note di frutti neri e cioccolato."}]',
 '["Degustazione 5 vini", "Pranzo con vista panoramica", "Visita barricaia", "Guida sommelier", "Aperitivo toscano", "Olio EVO degustazione"]',
 '["Trasporto", "Extra bevande", "Acquisto vini"]',
 '{"address": "Strada Provinciale 2, Castelnuovo Berardenga", "meeting_point": "Reception della tenuta", "parking_available": true, "accessibility_notes": "Completamente accessibile"}',
 '["tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]',
 '["11:00", "15:00"]',
 '["it", "en", "fr"]',
 'intermediate',
 18,
 'Si richiede abbigliamento elegante casual. Non adatto a bambini sotto i 12 anni.',
 'Cancellazione gratuita fino a 24 ore prima. Cancellazioni tardive: trattenuta del 25%.',
 '[]'),

-- Azienda Vinicola Monteverdi packages
('pkg44444-4444-4444-4444-444444444444',
 'c3d4e5f6-g7h8-9012-cdef-345678901234',
 'Vini dei Colli Euganei e Natura',
 'vini-colli-euganei-natura',
 'Scoperta dei vitigni autoctoni veneti in un contesto naturalistico unico. Degustazione di 5 vini da vitigni rari (Fior d''Arancio, Serprino, Pinello) con spiegazione delle caratteristiche pedoclimatiche dei Colli Euganei. Include passeggiata nei vigneti con vista sul Parco Regionale, merenda con prodotti locali biologici.',
 65.00,
 15,
 150,
 '[{"name": "Fior d''Arancio DOCG", "type": "dessert", "vintage": 2021, "grape_varieties": ["Moscato Giallo"], "tasting_notes": "Dolce e aromatico, note di fiori d''arancio e miele."}, {"name": "Serprino Frizzante", "type": "sparkling", "vintage": 2022, "grape_varieties": ["Glera"], "tasting_notes": "Fresco e vivace, perlage fine e persistente."}, {"name": "Colli Euganei Rosso", "type": "red", "vintage": 2020, "grape_varieties": ["Merlot", "Cabernet"], "tasting_notes": "Morbido e avvolgente, frutti rossi maturi."}]',
 '["Degustazione 5 vini autoctoni", "Passeggiata guidata vigneti", "Merenda biologica", "Guida naturalistica", "Vista panoramica", "Prodotti km zero"]',
 '["Trasporto", "Pranzo completo"]',
 '{"address": "Via Garibaldi 45, Vo Euganei", "meeting_point": "Parcheggio cantina", "parking_available": true, "accessibility_notes": "Percorso parzialmente accessibile", "coordinates": {"latitude": 45.3167, "longitude": 11.6333}}',
 '["friday", "saturday", "sunday"]',
 '["15:00", "17:00"]',
 '["it", "en"]',
 'beginner',
 16,
 'Scarpe comode per camminata. Possibilità di incontro con animali della fattoria.',
 'Cancellazione gratuita fino a 24 ore prima.',
 '[]'),

-- Castello di Montefalco packages
('pkg55555-5555-5555-5555-555555555555',
 'd4e5f6g7-h8i9-0123-defg-456789012345',
 'Sagrantino Masterclass',
 'sagrantino-masterclass',
 'Masterclass esclusiva dedicata al principe dei vini umbri. Degustazione verticale di Sagrantino di Montefalco DOCG di 5 annate diverse (2015-2020) con analisi tecnica delle caratteristiche organolettiche. Include visita al castello medievale, alle cantine storiche e cena degustazione con piatti della tradizione umbra abbinati.',
 185.00,
 6,
 240,
 '[{"name": "Sagrantino di Montefalco DOCG 2020", "type": "red", "vintage": 2020, "alcohol_content": 15.5, "grape_varieties": ["Sagrantino"], "tasting_notes": "Giovane e potente, tannini importanti, note di frutti neri."}, {"name": "Sagrantino di Montefalco DOCG 2018", "type": "red", "vintage": 2018, "grape_varieties": ["Sagrantino"], "tasting_notes": "Evoluto, note di spezie, cioccolato e tabacco."}, {"name": "Sagrantino di Montefalco DOCG 2015", "type": "red", "vintage": 2015, "grape_varieties": ["Sagrantino"], "tasting_notes": "Maturo ed elegante, note terziarie complesse."}]',
 '["Degustazione verticale 5 Sagrantino", "Visita castello medievale", "Cena degustazione umbra", "Sommelier esperto", "Materiale didattico avanzato", "Certificato partecipazione"]',
 '["Trasporto", "Pernottamento", "Extra vini"]',
 '{"address": "Via del Castello 1, Montefalco", "meeting_point": "Portone principale castello", "parking_available": true, "accessibility_notes": "Scalinate storiche, non completamente accessibile"}',
 '["friday", "saturday"]',
 '["18:00"]',
 '["it", "en"]',
 'expert',
 21,
 'Esperienza riservata a intenditori. Dress code elegante richiesto.',
 'Cancellazione gratuita fino a 1 settimana prima. Oltre i termini: rimborso del 30%.',
 '[]'),

-- Vigna del Mare packages
('pkg66666-6666-6666-6666-666666666666',
 'e5f6g7h8-i9j0-1234-efgh-567890123456',
 'Cinque Terre Wine Sunset',
 'cinque-terre-wine-sunset',
 'Esperienza unica al tramonto nelle Cinque Terre patrimonio UNESCO. Degustazione di 4 vini tipici (Cinque Terre DOC bianco, Sciacchetrà DOCG) su terrazza panoramica a strapiombo sul mare. Include spiegazione della viticoltura eroica sui terrazzamenti storici, aperitivo con focaccia ligure e vista indimenticabile sul mar Ligure.',
 95.00,
 12,
 90,
 '[{"name": "Cinque Terre DOC Bianco", "type": "white", "vintage": 2022, "grape_varieties": ["Bosco", "Albarola", "Vermentino"], "tasting_notes": "Fresco e minerale, note marine e agrumi."}, {"name": "Cinque Terre DOC Bianco Riserva", "type": "white", "vintage": 2021, "grape_varieties": ["Bosco", "Albarola"], "tasting_notes": "Più strutturato, note di frutta matura e erbe aromatiche."}, {"name": "Sciacchetrà DOCG", "type": "dessert", "vintage": 2019, "grape_varieties": ["Bosco", "Albarola", "Vermentino"], "tasting_notes": "Dolce passito, miele, frutta secca e note saline."}]',
 '["Degustazione 4 vini", "Vista panoramica mare", "Aperitivo focaccia ligure", "Tramonto guidato", "Storia viticoltura eroica", "Foto ricordo"]',
 '["Trasporto", "Cena", "Bevande extra"]',
 '{"address": "Via Litoranea 78, Riomaggiore", "meeting_point": "Stazione ferroviaria Riomaggiore", "parking_available": false, "accessibility_notes": "Scalinate ripide, non accessibile a disabili motori"}',
 '["thursday", "friday", "saturday", "sunday"]',
 '["18:30"]',
 '["it", "en", "fr", "de"]',
 'beginner',
 18,
 'Scarpe antiscivolo obbligatorie. Esperienza soggetta a condizioni meteo.',
 'Cancellazione per maltempo: rimborso completo. Altre cancellazioni: 48 ore prima.',
 '[]');