FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
#RUN npm ci --only=production
RUN npm install --production
# Copy source code
COPY . .

# Create non-root user
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nodeuser -u 1001
USER nodeuser

EXPOSE 3001

CMD ["npm", "start"]
